### ISSUE TITLE
No file created (or I don't know where it is)

### ISSUE THREAD

**Issue by rchastain** [paweld/simple-logger#1]
Hello! The project sounds interesting, but I can't get to make a working demo. No log file is created, or I don't know where it is.

Here is my demo program _demo.pas_:

```
uses
{$ifdef unix}
  CThreads,
{$endif}
  SysUtils,
  LPDLogU;
  
begin
  Logger.AddLog('Some text', ltInfo);
end.
```

Did I miss something?

**Comment by paweld** [comment]
Hello Roland,
file should form in the directory with the program.
I tested on Linux and found that there was an error. I have fixed it - try it now.

Best regards

**Comment by rchastain** [comment]
Thank you, but still no log file. I am also on Linux.

**Comment by paweld** [comment]
Hello Roland,
Thank you for your interest. 
The error is related to the program running too short, and the log does not manage to be saved to a file. I have applied a fix in the latest version, which in Windows solves this problem, but unfortunately under Linux it still occurs. I will try to identify the problem and get back to you with information.

**Comment by rchastain** [comment]
Thanks. I will try the unit in a real program.

**Comment by rchastain** [comment]
This example works. I think we can close the issue.

```
uses
{$ifdef unix}
  CThreads,
{$endif}
  SysUtils,
  LPDLogU;

var
  i: integer;
  
begin
  for i := 0 to 9 do
  begin
    Logger.AddLog('Some text', ltInfo);
    Sleep(500);
  end;
end.
```

**Comment by paweld** [comment]
On Linux for such a simple program just add `sleep(1000);` to the end of the code, for example:
```pascal
uses
{$ifdef unix}
  CThreads,
{$endif}
  SysUtils,
  LPDLogU;

var
  i: integer;
  
begin
  for i := 0 to 9 do
    Logger.AddLog('Some text', ltInfo);
  Sleep(1000);
end.
```

**Comment by rchastain** [comment]
I made a simple Lazarus demo. The application crashes and creates an empty _demo.log_ file.

```
[roland@localhost lazdemo (master)]$ ./demo
realloc(): invalid pointer
Abandon (core dumped)
```

[lazdemo.zip](https://github.com/paweld/simple-logger/files/14228712/lazdemo.zip)

**Comment by paweld** [comment]
Can you attach the whole project? I'm checking on Debian 12 xfce, Lazarus trunk (3.99), fpc 3.2-fixes and I don't get the error

**Comment by rchastain** [comment]
Sorry, I believed I had attached the whole project. Here it is.

[lazdemo.zip](https://github.com/paweld/simple-logger/files/14228849/lazdemo.zip)

**Comment by paweld** [comment]
you must add `cmem` unit in uses section `lpr` file, ie.
```pascal
program demo;

{$mode objfpc}{$H+}

uses
  {$IFDEF UNIX}
  cmem, cthreads,
  {$ENDIF}       
  //...
```

**Comment by rchastain** [comment]
Yes, it works. Thank you.

**Comment by paweld** [comment]
You're welcome.
